### ISSUE TITLE
esp8266 rtos addition

### ISSUE THREAD

**Issue by willemwouters** [Gabriel-LG/esp_mod_sdk#1]
Hi,

I tried to create a Pull request, but because of some restructuring impossible.

But I forked your code, and added the esp_rtos sdk in the same line as your build system.

Maybe worth a copy?

https://github.com/willemwouters/ESP8266_Modular

**Comment by Gabriel-LG** [comment]
Hi Willem,

Thank you for your message and for making an effort!
I was working on the exact same thing and the result was almost identical, how bizar.
My work integrated the esp_rtos_iot_sdk repo by means of subtree (hopefully this will allow for easy pulling updates from espressif). If it weren't for this, I would have pulled your changes.

kind regards,
Gabriel-LG

**Comment by Gabriel-LG** [comment]
Hi Willem,

Thank you for your message and for making an effort!
I was working on the exact same thing and the result was almost identical,
how bizar.
My work integrated the esp_rtos_iot_sdk repo by means of subtree (hopefully
this will allow for easy pulling updates from espressif). If it weren't for
this, I would have pulled your changes.

kind regards,
Gabriel-LG
